//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXe_HaVanNua_1911080070
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public string LoaiXe { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string Khu { get; set; }
        public Nullable<int> SoCho { get; set; }
    }
}
