//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXe_HaVanNua_1911080070
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSXeTrongBai
    {
        public string IDXeVao { get; set; }
        public string BienSo { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public string LoaiXe { get; set; }
        public string GhiChu { get; set; }
        public string MaTheXe { get; set; }
        public string MaBai { get; set; }
    }
}
