//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXe_HaVanNua_1911080070
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBaiGiuXe : DbContext
    {
        public QuanLyBaiGiuXe()
            : base("name=QuanLyBaiGiuXe")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bai> Bais { get; set; }
        public virtual DbSet<BangGia> BangGias { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<TheXe> TheXes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XeRa> XeRas { get; set; }
        public virtual DbSet<XeVao> XeVaos { get; set; }
        public virtual DbSet<SuCo> SuCoes { get; set; }
        public virtual DbSet<PhieuThanhToan> PhieuThanhToans { get; set; }
    }
}
