//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXe_HaVanNua_1911080070
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheXe
    {
        public string MaTheXe { get; set; }
        public string MaXe { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public string MaKhach { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    }
}
