//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiGiuXe_HaVanNua_1911080070
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeRa
    {
        public string MaXeRa { get; set; }
        public string BienSo { get; set; }
        public string MaTheXe { get; set; }
        public string LoaiXe { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<int> ThoiGianGui { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    }
}
